name: pantalla_consentimiento
description: A sample command-line application with basic argument parsing.
version: 0.0.1
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ">=3.9.0 <4.0.0"

# Add regular dependencies here.
dependencies:
  flutter:
    sdk: flutter
  permission_handler: ^11.3.1
  shared_preferences: ^2.3.2
  args: ^2.7.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
  flutter_test:
    sdk: flutter
